In [2]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

sys.path.append(str(PROJECT_ROOT))

print(PROJECT_ROOT)

c:\Users\muche\Documents\GitHub\SentinelAI

In [ ]:
from machine_learning.data_pipeline.dataset_builder import DatasetBuilder
from machine_learning.data_pipeline.risk_label import calculate_risk

print("SentinelAI modules loaded successfully")

In [3]:
from machine_learning.data_pipeline.dataset_builder import DatasetBuilder
from machine_learning.data_pipeline.risk_label import calculate_risk


builder = DatasetBuilder()


weather = builder.load_weather(
    "../data/raw/weather/weather_sample.csv"
)


population = builder.load_population(
    "../data/raw/population/population.csv"
)


dataset = builder.merge_data(
    weather,
    population
)


dataset["risk_level"] = dataset.apply(
    calculate_risk,
    axis=1
)


dataset

,location,date,rainfall,temperature,humidity,population,density,poverty_rate,risk_level
0,Turkana,2025-01-01,120,31,40,950000,13,65,MEDIUM
1,Turkana,2025-02-01,80,33,35,950000,13,65,HIGH
2,Turkana,2025-03-01,200,29,60,950000,13,65,MEDIUM
3,Garissa,2025-01-01,50,35,30,850000,12,55,HIGH
4,Garissa,2025-02-01,70,36,32,850000,12,55,HIGH
5,Garissa,2025-03-01,150,34,55,850000,12,55,MEDIUM

In [5]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

print("EDA environment ready")

ModuleNotFoundError: No module named 'matplotlib'

In [7]:
dataset_path = "../data/processed/risk_training_dataset.csv"

df = pd.read_csv(dataset_path)

df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../data/processed/risk_training_dataset.csv'

In [8]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

sys.path.append(str(PROJECT_ROOT))

print(PROJECT_ROOT)

c:\Users\muche\Documents\GitHub\SentinelAI

In [9]:
from machine_learning.data_pipeline.dataset_builder import DatasetBuilder
from machine_learning.data_pipeline.risk_label import calculate_risk

print("Modules loaded")

Modules loaded

In [10]:
builder = DatasetBuilder()


weather = builder.load_weather(
    "../data/raw/weather/weather_sample.csv"
)


population = builder.load_population(
    "../data/raw/population/population.csv"
)


weather.head()

  location        date  rainfall  temperature  humidity
0  Turkana  2025-01-01       120           31        40
1  Turkana  2025-02-01        80           33        35
2  Turkana  2025-03-01       200           29        60
3  Garissa  2025-01-01        50           35        30
4  Garissa  2025-02-01        70           36        32

In [11]:
dataset = builder.merge_data(
    weather,
    population
)


dataset

,location,date,rainfall,temperature,humidity,population,density,poverty_rate
0,Turkana,2025-01-01,120,31,40,950000,13,65
1,Turkana,2025-02-01,80,33,35,950000,13,65
2,Turkana,2025-03-01,200,29,60,950000,13,65
3,Garissa,2025-01-01,50,35,30,850000,12,55
4,Garissa,2025-02-01,70,36,32,850000,12,55
5,Garissa,2025-03-01,150,34,55,850000,12,55

In [12]:
dataset["risk_level"] = dataset.apply(
    calculate_risk,
    axis=1
)


dataset

,location,date,rainfall,temperature,humidity,population,density,poverty_rate,risk_level
0,Turkana,2025-01-01,120,31,40,950000,13,65,MEDIUM
1,Turkana,2025-02-01,80,33,35,950000,13,65,HIGH
2,Turkana,2025-03-01,200,29,60,950000,13,65,MEDIUM
3,Garissa,2025-01-01,50,35,30,850000,12,55,HIGH
4,Garissa,2025-02-01,70,36,32,850000,12,55,HIGH
5,Garissa,2025-03-01,150,34,55,850000,12,55,MEDIUM

In [13]:
builder.dataset = dataset


builder.save_dataset(
    "../data/processed/risk_training_dataset.csv"
)

In [ ]:
import pandas as pd
import numpy as np

from pathlib import Path

from machine_learning.data_pipeline.dataset_builder import DatasetBuilder

In [1]:
import pandas as pd
import numpy as np

from pathlib import Path

from machine_learning.data_pipeline.dataset_builder import DatasetBuilder

In [2]:
raw_path = "../data/raw"

processed_path = "../data/processed/risk_training_dataset.csv"

In [3]:
data = {


    "temperature": [

        38,
        32,
        25,
        40,
        28,
        35,
        22,
        37,
        30,
        26

    ],


    "rainfall": [

        10,
        80,
        150,
        5,
        120,
        20,
        200,
        15,
        90,
        130

    ],


    "humidity": [

        20,
        60,
        80,
        15,
        75,
        25,
        90,
        30,
        65,
        85

    ],



    "population": [

        1000000,
        500000,
        200000,
        1500000,
        300000,
        900000,
        150000,
        1200000,
        400000,
        250000

    ],



    "density": [

        150,
        40,
        10,
        200,
        20,
        120,
        5,
        180,
        50,
        15

    ],



    "poverty_rate": [

        75,
        40,
        20,
        80,
        25,
        65,
        15,
        70,
        35,
        30

    ],



    "ndvi": [

        0.15,
        0.55,
        0.80,
        0.10,
        0.75,
        0.25,
        0.90,
        0.20,
        0.60,
        0.85

    ],



    "rainfall_anomaly": [

        -40,
        10,
        30,
        -50,
        20,
        -25,
        40,
        -35,
        5,
        25

    ]

}



raw_df = pd.DataFrame(data)


raw_df.head()

,temperature,rainfall,humidity,population,density,poverty_rate,ndvi,rainfall_anomaly
0,38,10,20,1000000,150,75,0.15,-40
1,32,80,60,500000,40,40,0.55,10
2,25,150,80,200000,10,20,0.80,30
3,40,5,15,1500000,200,80,0.10,-50
4,28,120,75,300000,20,25,0.75,20

In [4]:
builder = DatasetBuilder()


dataset = builder.create_dataset(

    raw_df.to_dict(
        orient="records"
    )

)


dataset.head()

,temperature,rainfall,humidity,population,density,poverty_rate,ndvi,rainfall_anomaly,risk_level
0,38,10,20,1000000,150,75,0.15,-40,HIGH
1,32,80,60,500000,40,40,0.55,10,LOW
2,25,150,80,200000,10,20,0.80,30,LOW
3,40,5,15,1500000,200,80,0.10,-50,HIGH
4,28,120,75,300000,20,25,0.75,20,LOW

In [5]:
dataset.columns

Index(['temperature', 'rainfall', 'humidity', 'population', 'density',
       'poverty_rate', 'ndvi', 'rainfall_anomaly', 'risk_level'],
      dtype='str')

In [6]:
dataset["risk_level"].value_counts()

risk_level
LOW     6
HIGH    4
Name: count, dtype: int64

In [7]:
builder.save_dataset(

    dataset,

    processed_path

)


print(
    "Dataset saved successfully"
)

Dataset saved successfully

In [8]:
df = pd.read_csv(

    "../data/processed/risk_training_dataset.csv"

)


df.head()

,temperature,rainfall,humidity,population,density,poverty_rate,ndvi,rainfall_anomaly,risk_level
0,38,10,20,1000000,150,75,0.15,-40,HIGH
1,32,80,60,500000,40,40,0.55,10,LOW
2,25,150,80,200000,10,20,0.80,30,LOW
3,40,5,15,1500000,200,80,0.10,-50,HIGH
4,28,120,75,300000,20,25,0.75,20,LOW