In [2]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

sys.path.append(str(PROJECT_ROOT))

print(PROJECT_ROOT)

c:\Users\muche\Documents\GitHub\SentinelAI

In [ ]:
from machine_learning.data_pipeline.dataset_builder import DatasetBuilder
from machine_learning.data_pipeline.risk_label import calculate_risk

print("SentinelAI modules loaded successfully")

In [3]:
from machine_learning.data_pipeline.dataset_builder import DatasetBuilder
from machine_learning.data_pipeline.risk_label import calculate_risk


builder = DatasetBuilder()


weather = builder.load_weather(
    "../data/raw/weather/weather_sample.csv"
)


population = builder.load_population(
    "../data/raw/population/population.csv"
)


dataset = builder.merge_data(
    weather,
    population
)


dataset["risk_level"] = dataset.apply(
    calculate_risk,
    axis=1
)


dataset

,location,date,rainfall,temperature,humidity,population,density,poverty_rate,risk_level
0,Turkana,2025-01-01,120,31,40,950000,13,65,MEDIUM
1,Turkana,2025-02-01,80,33,35,950000,13,65,HIGH
2,Turkana,2025-03-01,200,29,60,950000,13,65,MEDIUM
3,Garissa,2025-01-01,50,35,30,850000,12,55,HIGH
4,Garissa,2025-02-01,70,36,32,850000,12,55,HIGH
5,Garissa,2025-03-01,150,34,55,850000,12,55,MEDIUM

In [5]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

print("EDA environment ready")

ModuleNotFoundError: No module named 'matplotlib'

In [7]:
dataset_path = "../data/processed/risk_training_dataset.csv"

df = pd.read_csv(dataset_path)

df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../data/processed/risk_training_dataset.csv'

In [8]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

sys.path.append(str(PROJECT_ROOT))

print(PROJECT_ROOT)

c:\Users\muche\Documents\GitHub\SentinelAI

In [9]:
from machine_learning.data_pipeline.dataset_builder import DatasetBuilder
from machine_learning.data_pipeline.risk_label import calculate_risk

print("Modules loaded")

Modules loaded

In [10]:
builder = DatasetBuilder()


weather = builder.load_weather(
    "../data/raw/weather/weather_sample.csv"
)


population = builder.load_population(
    "../data/raw/population/population.csv"
)


weather.head()

  location        date  rainfall  temperature  humidity
0  Turkana  2025-01-01       120           31        40
1  Turkana  2025-02-01        80           33        35
2  Turkana  2025-03-01       200           29        60
3  Garissa  2025-01-01        50           35        30
4  Garissa  2025-02-01        70           36        32

In [11]:
dataset = builder.merge_data(
    weather,
    population
)


dataset

,location,date,rainfall,temperature,humidity,population,density,poverty_rate
0,Turkana,2025-01-01,120,31,40,950000,13,65
1,Turkana,2025-02-01,80,33,35,950000,13,65
2,Turkana,2025-03-01,200,29,60,950000,13,65
3,Garissa,2025-01-01,50,35,30,850000,12,55
4,Garissa,2025-02-01,70,36,32,850000,12,55
5,Garissa,2025-03-01,150,34,55,850000,12,55

In [12]:
dataset["risk_level"] = dataset.apply(
    calculate_risk,
    axis=1
)


dataset

,location,date,rainfall,temperature,humidity,population,density,poverty_rate,risk_level
0,Turkana,2025-01-01,120,31,40,950000,13,65,MEDIUM
1,Turkana,2025-02-01,80,33,35,950000,13,65,HIGH
2,Turkana,2025-03-01,200,29,60,950000,13,65,MEDIUM
3,Garissa,2025-01-01,50,35,30,850000,12,55,HIGH
4,Garissa,2025-02-01,70,36,32,850000,12,55,HIGH
5,Garissa,2025-03-01,150,34,55,850000,12,55,MEDIUM

In [13]:
builder.dataset = dataset


builder.save_dataset(
    "../data/processed/risk_training_dataset.csv"
)

In [ ]:
import pandas as pd
import numpy as np

from pathlib import Path

from machine_learning.data_pipeline.dataset_builder import DatasetBuilder