In [1]:
import sys
from pathlib import Path


PROJECT_ROOT = Path.cwd().parent


sys.path.append(
    str(PROJECT_ROOT)
)

In [2]:
from machine_learning.pipeline.risk_pipeline import run_risk_pipeline

In [5]:
weather = {

    "rainfall":50,

    "temperature":35,

    "humidity":30

}



population = {

    "population":850000,

    "density":12,

    "poverty_rate":55

}



satellite = {

    "ndvi":0.25

}

In [6]:
result = run_risk_pipeline(

    weather,

    population,

    satellite

)


result

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- ndvi
Feature names seen at fit time, yet now missing:
- rainfall

In [7]:
result = run_risk_pipeline(

    weather,

    population,

    satellite

)


result

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- ndvi
Feature names seen at fit time, yet now missing:
- rainfall

In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

sys.path.append(
    str(PROJECT_ROOT)
)

print(PROJECT_ROOT)

c:\Users\muche\Documents\GitHub\SentinelAI

In [2]:
import importlib

import machine_learning.pipeline.feature_builder
import machine_learning.pipeline.risk_pipeline


importlib.reload(
    machine_learning.pipeline.feature_builder
)


importlib.reload(
    machine_learning.pipeline.risk_pipeline
)


from machine_learning.pipeline.risk_pipeline import run_risk_pipeline

In [3]:
from machine_learning.pipeline.feature_builder import build_features


features = build_features(
    weather,
    population,
    satellite
)


features

NameError: name 'weather' is not defined

In [4]:
weather = {

    "rainfall": 50,

    "temperature": 35,

    "humidity": 30

}


population = {

    "population": 850000,

    "density": 12,

    "poverty_rate": 55

}


satellite = {

    "ndvi": 0.25

}

In [5]:
from machine_learning.pipeline.feature_builder import build_features


features = build_features(
    weather,
    population,
    satellite
)


features

   rainfall  temperature  humidity  population  density  poverty_rate
0        50           35        30      850000       12            55

In [6]:
from machine_learning.pipeline.risk_pipeline import run_risk_pipeline


result = run_risk_pipeline(
    weather,
    population,
    satellite
)


result

{'risk_score': np.int64(2)}

In [1]:
result

NameError: name 'result' is not defined

In [2]:
result

NameError: name 'result' is not defined

In [3]:
result = run_risk_pipeline(
    weather,
    population,
    satellite
)

result

NameError: name 'run_risk_pipeline' is not defined

In [4]:
from machine_learning.pipeline.risk_pipeline import run_risk_pipeline

ModuleNotFoundError: No module named 'backend'

In [5]:
import sys
from pathlib import Path


PROJECT_ROOT = Path.cwd().parent


sys.path.append(
    str(PROJECT_ROOT)
)


print(PROJECT_ROOT)

c:\Users\muche\Documents\GitHub\SentinelAI

In [6]:
from machine_learning.pipeline.risk_pipeline import run_risk_pipeline

In [7]:
weather = {

    "temperature":40,

    "humidity":20,

    "rainfall":10

}


population = {

    "population":1000000,

    "density":150,

    "poverty_rate":75

}


satellite = {

    "ndvi":0.15,

    "rainfall_anomaly":-40

}

In [8]:
result = run_risk_pipeline(

    weather,

    population,

    satellite

)


result

KeyError: "['ndvi', 'rainfall_anomaly'] not in index"

In [9]:
result = run_risk_pipeline(

    weather,

    population,

    satellite

)


result

KeyError: "['ndvi', 'rainfall_anomaly'] not in index"

In [10]:
from machine_learning.pipeline.feature_builder import build_features

In [11]:
features = build_features(

    weather,

    population,

    satellite

)


features

   rainfall  temperature  humidity  population  density  poverty_rate
0        10           40        20     1000000      150            75

In [12]:
result = run_risk_pipeline(
    weather,
    population,
    satellite
)

KeyError: "['ndvi', 'rainfall_anomaly'] not in index"

In [13]:
result = run_risk_pipeline(
    weather,
    population,
    satellite
)

KeyError: "['ndvi', 'rainfall_anomaly'] not in index"

In [14]:
features = build_features(
    weather,
    population,
    satellite
)

features

   rainfall  temperature  humidity  population  density  poverty_rate
0        10           40        20     1000000      150            75

In [15]:
result = run_risk_pipeline(
    weather,
    population,
    satellite
)

result

KeyError: "['ndvi', 'rainfall_anomaly'] not in index"

In [16]:
from machine_learning.pipeline.feature_builder import build_features


features = build_features(
    weather,
    population,
    satellite
)


print(features.columns)

features

Index(['rainfall', 'temperature', 'humidity', 'population', 'density',
       'poverty_rate'],
      dtype='str')

   rainfall  temperature  humidity  population  density  poverty_rate
0        10           40        20     1000000      150            75

In [17]:
import machine_learning.pipeline.feature_builder as fb

print(fb.__file__)

C:\Users\muche\Documents\GitHub\SentinelAI\machine_learning\pipeline\feature_builder.py

In [18]:
import importlib

import machine_learning.pipeline.feature_builder as fb


importlib.reload(fb)


print(fb.__file__)

C:\Users\muche\Documents\GitHub\SentinelAI\machine_learning\pipeline\feature_builder.py

In [19]:
features = fb.build_features(
    weather,
    population,
    satellite
)


print(features.columns)

features

Index(['temperature', 'rainfall', 'humidity', 'population', 'density',
       'poverty_rate', 'ndvi', 'rainfall_anomaly'],
      dtype='str')

,temperature,rainfall,humidity,population,density,poverty_rate,ndvi,rainfall_anomaly
0,40,10,20,1000000,150,75,0.15,-40

In [20]:
result = run_risk_pipeline(

    weather,

    population,

    satellite

)


result

KeyError: "['ndvi', 'rainfall_anomaly'] not in index"

In [21]:
from machine_learning.pipeline.risk_pipeline import run_risk_pipeline

In [22]:
result = run_risk_pipeline(
    weather,
    population,
    satellite
)

result

KeyError: "['ndvi', 'rainfall_anomaly'] not in index"

In [23]:
import backend.services.prediction as pred

print(pred.__file__)

c:\Users\muche\Documents\GitHub\SentinelAI\backend\services\prediction.py

In [24]:
import importlib
import backend.services.prediction as pred

importlib.reload(pred)

print(pred.__file__)

Loaded model: C:\Users\muche\Documents\GitHub\SentinelAI\machine_learning\models\risk_classifier.pkl
Model features: ['temperature' 'rainfall' 'humidity' 'population' 'density' 'poverty_rate'
 'ndvi' 'rainfall_anomaly']
c:\Users\muche\Documents\GitHub\SentinelAI\backend\services\prediction.py

In [25]:
import machine_learning.pipeline.risk_pipeline as rp

importlib.reload(rp)

In [26]:
from machine_learning.pipeline.risk_pipeline import run_risk_pipeline

In [27]:
result = run_risk_pipeline(

    weather,

    population,

    satellite

)

result

Index(['temperature', 'rainfall', 'humidity', 'population', 'density',
       'poverty_rate', 'ndvi', 'rainfall_anomaly'],
      dtype='str')

PREDICTION INPUT FEATURES
Index(['temperature', 'rainfall', 'humidity', 'population', 'density',
       'poverty_rate', 'ndvi', 'rainfall_anomaly'],
      dtype='str')
   temperature  rainfall  humidity  population  density  poverty_rate  ndvi  \
0         40.0      10.0      20.0   1000000.0    150.0          75.0  0.15

   rainfall_anomaly
0             -40.0

{'risk_score': {'risk_level': 'HIGH',
  'risk_score': 100,
  'confidence': np.float64(98.5),
  'model_prediction': '0',
  'features': {'temperature': 40.0,
   'rainfall': 10.0,
   'humidity': 20.0,
   'population': 1000000.0,
   'density': 150.0,
   'poverty_rate': 75.0,
   'ndvi': 0.15,
   'rainfall_anomaly': -40.0}}}

In [28]:
result = run_risk_pipeline(

    weather,

    population,

    satellite

)


result

Index(['temperature', 'rainfall', 'humidity', 'population', 'density',
       'poverty_rate', 'ndvi', 'rainfall_anomaly'],
      dtype='str')

PREDICTION INPUT FEATURES
Index(['temperature', 'rainfall', 'humidity', 'population', 'density',
       'poverty_rate', 'ndvi', 'rainfall_anomaly'],
      dtype='str')
   temperature  rainfall  humidity  population  density  poverty_rate  ndvi  \
0         40.0      10.0      20.0   1000000.0    150.0          75.0  0.15

   rainfall_anomaly
0             -40.0

{'risk_score': {'risk_level': 'HIGH',
  'risk_score': 100,
  'confidence': np.float64(98.5),
  'model_prediction': '0',
  'features': {'temperature': 40.0,
   'rainfall': 10.0,
   'humidity': 20.0,
   'population': 1000000.0,
   'density': 150.0,
   'poverty_rate': 75.0,
   'ndvi': 0.15,
   'rainfall_anomaly': -40.0}}}